version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_personal_website
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - personal-website
    networks:
      - personal-website-network

  # Production service (nginx serving built files)
  personal-website:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - REACT_APP_API_URL=https://shivpalit.com
    container_name: personal-website
    environment:
      - REACT_APP_API_URL=https://shivpalit.com
    networks:
      - personal-website-network

  # Development service (React dev server with hot-reloading)
  personal-website-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: personal-website-dev
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - personal-website-network

  backend-flask:
    build:
      context: ./backend-flask
      dockerfile: Dockerfile
    container_name: backend-flask
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - OPENAI_KEY=${OPENAI_KEY}
    volumes:
      - ./backend-flask:/app
    restart: unless-stopped
    networks:
      - personal-website-network

networks:
  personal-website-network:
    driver: bridge 